services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"  # Expose SonarQube on port 9000
    networks:
      - projet_devops_sonar_network
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_plugins:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_conf:/opt/sonarqube/conf

  sonarqube_db:
    image: postgres:alpine
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projet_devops_sonar_network

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    ports:
      - "8081:8081"  # Expose Nexus on port 8081
    networks:
      - projet_devops_sonar_network
    volumes:
      - nexus_data:/nexus-data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - projet_devops_sonar_network

networks:
  projet_devops_sonar_network:
    external: true  # Ensure this network is external and not recreated

volumes:
  sonarqube_data:
    external: true
    name: 5a5a574f8570ecaa0b22ee8bd6ea0878964d03e68760f4d3e079bb9910e40255
  sonarqube_plugins:
    external: true
    name: 3626d5180edfefc97c29e62917e6e119a7dbb79dfe8fd7a484e6223313b4d415
  sonarqube_logs:
    external: true
    name: 612348833d5fe1537f03f03f65b20dd0887fbb5970ffdb86294a9fa60fbc6603
  sonarqube_conf:
    external: true
    name: 6975c9d889319db1e7a122b6ce750725593dc51a80ec2d0425508dbbec003202
  sonarqube_data_external:
    external: true
    name: eb353ca7b3ac66349b79bc223b0fe96197975205ff2cbb560341c17ffbb3833
  postgres_data:
    external: false
  nexus_data:
    external: true
    name: 1081e2145f9f9160f02f37677b0752ffc68ed7cbeb0d5b9f4f546bfefbcb4c60
  mysql_data:
    external: false
    name: d36ab1b6f764c1f05c1931e76b355ed53770c930eccf252d10aac933b987f885

