version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    image: shark58/sonarqube:latest
    # Uncomment the line below if you want to build from a Dockerfile in the current directory
    # build: . 
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tpfoyer_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    image: shark58/sonarqube:latest
    # Uncomment the line below if you want to build from a Dockerfile in the current directory
    # build: . 
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
