services:
  mysqldb:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rachid_db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:

